### ISSUE TITLE
In tests, put processing speed in an output file (i.e. xls) instead of printing it on the terminal

### ISSUE THREAD

**Issue by VeraPrinsen** [VeraPrinsen/isomorphisms#30]

**Comment by mvandermade** [comment]
![afbeelding](https://user-images.githubusercontent.com/33425497/54036056-ef898380-41ba-11e9-9a44-5d26fcf70b4a.png)

https://realpython.com/python-csv/

```
import csv

with open('employee_file.csv', mode='w') as employee_file:
    employee_writer = csv.writer(employee_file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)

    employee_writer.writerow(['John Smith', 'Accounting', 'November'])
    employee_writer.writerow(['Erica Meyers', 'IT', 'March'])
```

**Comment by JKleinRot** [comment]
Een test file om alle tests te runnen.
CSV file per test voor tijden van runnen en resultaat.
Niet overschrijven van csv file. 
Mappen dot, png, csv aanmaken als ze er nog niet zijn.
In de commandline alleen passed of failed zetten en voor de failed testen welke dat zijn.
