### ISSUE TITLE
Create a file to run all tests from and output results to csv

### ISSUE THREAD

**Issue by mvandermade** [VeraPrinsen/isomorphisms#52]
Deze issue neemt de overgebleven punten over van closed #30 

- Een test file om alle tests te runnen.
- CSV file per test voor tijden van runnen en resultaat.
- In de commandline alleen passed of failed zetten en voor de failed (sub)testen welke dat zijn.

Ik stel voor om eerst 1 test om te bouwen in een PR.

**Comment by VeraPrinsen** [comment]
* alle aparte tests aanpassen. Binnen elke test een methode test(write_to_csv, console_pass, console_fail) bijvoorbeeld waarin je de test kan aanroepen met de booleans welke output je wil creeren.
* Binnen elke aparte test een aanroep binnen __name__ is __main__ van de test()
* In een run_all_tests file alle aparte tests aanroepen.
