### ISSUE TITLE
Improve fast_color_refinement

### ISSUE THREAD

**Issue by JKleinRot** [VeraPrinsen/isomorphisms#53]
Nu duurt de methode om de neighbours van de color group te krijgen er lang, daar zit ook de meeste kennis in. Dit kan wellicht sneller. 
Ook is er nog het ding dat nu de grotere groep wordt toegevoegd aan de queue ipv de kleinere, maar dit levert wel sneller resultaat op dan hoe het in de slides beschreven staat. Hier moet eigenlijk ook nog naar gekeken worden.

**Comment by mvandermade** [comment]
Voor info color group:
https://github.com/VeraPrinsen/isomorphisms/pull/48#discussion_r265599080

**Comment by VeraPrinsen** [comment]
En net zoals bij de gewone color_refinement, zouden we - als we weten dat we op zoek zijn naar isomorphisms met een disjoint union van 2 grafen - na elke cycle dat er iets veranderd is kunnen kijken of de kleuring nog balanced is en anders terminaten.
