### ISSUE TITLE
Improve copy in graph

### ISSUE THREAD

**Issue by VeraPrinsen** [VeraPrinsen/isomorphisms#67]

**Comment by JKleinRot** [comment]
Ik heb net even wat geprobeerd, maar kreeg het nog niet sneller. Ik denk dat we op dit moment ook meer tijd kunnen winnen in de branching zelf dan in deze methode. Maar wel goed om te laten staan voor als we nog tijd over hebben.

**Comment by mvandermade** [comment]
ik heb in test van branching.py console logging toegevoegd van de .copy() actie.

**Comment by VeraPrinsen** [comment]
Inmiddels is de branching al aangepast, zodat de copy() niet zo vaak meer gebruikt wordt

**Comment by mvandermade** [comment]
issue kan wat mij betreft gesloten worden
