### ISSUE TITLE
ModulesC graph 2 and 4 cannot be determined yet

### ISSUE THREAD

**Issue by VeraPrinsen** [VeraPrinsen/isomorphisms#92]
Misschien even kijken of we nog kunnen ontdekken waarom deze zo langzaam is

**Comment by JKleinRot** [comment]
Heb er naar gekeken voordat de snellere branching erin zat. Toen kon ik niet wat vinden wat afwijkend leek. Misschien dat de snellere branching helpt met het oplossen van dit probleem.

**Comment by VeraPrinsen** [comment]
Kan met de snellere branching
